apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: khg7rxy7w-dotnet-basic
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: khg7rxy7w-dotnet-basic 
  name: khg7rxy7w-dotnet-basic
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: khg7rxy7w-dotnet-basic 
